### PR TITLE
Team3 question7

### PR DESCRIPTION
**Pull request by santacruzm**
WIP: Here is the work that Jordan and I have completed

### CODE REVIEW

**Review by Jordan-A — DISMISSED** [review]

**Comment by liux2** [comment]
Could you divide the paragraph into 3 - 5 paragraphs with bullet point title? The structure can be found at the master branch.

**Comment by liux2** [comment]
Nevermind, the majority of the people are doing a one-paragraph answer. I made the comment because the professor mentioned 3-5 points per answer. Then we decide to use bullet points. After someone suggested using "paragraph" instead of bullet points, now we have a 3-5 sentence paragraph requirement.

**Comment by liux2** [comment]
Good work, I don't see any problems for now.

**Review by liux2 — APPROVED** [review]

**Review by enpuyou — CHANGES_REQUESTED** [review]
It seems like this part didn't directly address when the postmortem should be conducted. Also, just to clarify, is the postmortems going to be conducted through issue tracker?

**Comment by santacruzm** [comment]
@enpuyou  
The postmortems should be addressed immediately or as soon as a team member notices the issue. And yes the issue along with the mindset of blameless post-mortems will be conducted through an issue tracker. With the issue tracker, team members can give this detailed account without fear of punishment or blame.  Does this add clarity?

**Comment by enpuyou** [comment]
@santacruzm I kind of think that postmortems happen after every small phase/cycle of the software engineering, to discuss what went well, what didn't, what actions were taken, what the effect was, and what could be learned. It does not have to be related to a specific issue. So I guess I view it not as an issue-based or bug-based thing but a necessary step to take in the development. I think I understand what you are saying and the issue tracker is great. Maybe even add a `postmortem` tag to the issue so it's not misunderstood as a real bug/issue. This is just my opinion. Thanks for clarifying!

**Comment by Jordan-A** [comment]
I just pushed an update to address the concerns that you have brought up @enpuyou.

They can be found here:
https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/888fcf3d2115de0e964d3b7442b7e6612c26e2a8
https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/e5883d40fc06ca208458023e1beabac372d87f79

**Review by Jordan-A — APPROVED** [review]

**Review by enpuyou — APPROVED** [review]

**Review by corlettim — APPROVED** [review]

**Pull request merged**
